int fibo(int,int*);
int concat(int*,int,int*,int,int*);
int reverse(int*,int);
int filter(int*,int,int,int**);
int reverseReturn(int*,int,int*);
int slice(int*,int,int,int,int**);
int isPrime(int);
int getPrimes(int**,int,int);
int strCmp(char*,char*);
int forEach(int*,int,void*);
int forEachChar(char*,int,void*);
int forEachString(char**,int,void(*)(char*,int,char**));
int filterArray(int*,int,int (*)(int, int, int *),int**);
int filterStrings(char**,int,int (*)(char*, int, char **),char***);
int* mapInt(int*,int,int(*)(int,int,int*));
char** mapString(char**,int,char* (*)(char*,int,char**));
int reduce(int*,int,int(*)(int,int,int,int*),int);
int indexOf(char*,char*);
char* reduceStrings(char**,int,char*(*)(char*,char*,int,char**));
// int isPalindrome(int);